### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by janstieler** [QL-Win/QuickLook.Plugin.OfficeViewer#9]
Hi,
I have a problem to install the quicklook plugin.
If I press the spacebar I get no install button only what you can see on the screenshot:

![Bildschirmfoto 2019-08-21 um 01 14 36](https://user-images.githubusercontent.com/754880/63390980-33f78d00-c3b1-11e9-96a8-aa083a52dc23.jpg)

**Comment by xupefei** [comment]
This project of for Windows but as I can see you are using macOS :)
Use these instead: https://github.com/sindresorhus/quick-look-plugins

**Comment by janstieler** [comment]
Oh, I havn't seen that this is for Windows and I doesn't know that are a Quicklook also available for Windows.
Than Sorry!

**Comment by hoangdesu** [comment]
Oh dear I have been spending the last hour looking for this without noticing this is for Windows lmao! Thanks a lot, you saved my life
